### ISSUE TITLE
Problem about introducing ControlNet to you model

### ISSUE THREAD

**Issue by Norman-Ou** [LeonHLJ/FouriScale#4]
Hi,

I introduce a ControlNet Module to your model, but the width and height of the latent that be the input to ControlNet are the same of target image width and height.

It is conflict to your setting that latent height(or width)= target height(or width) // 8

**Comment by LeonHLJ** [comment]
> Hi,
> 
> I introduce a ControlNet Module to your model, but the width and height of the latent that be the input to ControlNet are the same of target image width and height.
> 
> It is conflict to your setting that latent height(or width)= target height(or width) // 8

Thanks for your attention. I can't catch what you said about "the width and height of the latent that be the input to ControlNet are the same as the target image width and height." In Sec. 3.2 of the paper on ControlNet, the height and width of the image condition for ControlNet should be 8&times; that of the latent input for ControlNet, in order to match the convolution size. If you try to use ControlNet with FouriScale, you should set the width/height of the image condition to be the same as the target image, the width/height of the latent input for ControlNet should also be the same as the latent for UNet.

**Comment by Norman-Ou** [comment]
Sorry for the unclear expression
